events {
    worker_connections 1024;
}

http {
    upstream id_backend {
        server id-server-1:8080 max_fails=2 fail_timeout=5s;
        server id-server-2:8080 max_fails=2 fail_timeout=5s;
        server id-server-3:8080 max_fails=2 fail_timeout=5s;
        server id-server-4:8080 max_fails=2 fail_timeout=5s;
        server id-server-5:8080 max_fails=2 fail_timeout=5s;
    }

    server {
        listen 80;

        location /api/ {
            proxy_pass http://id_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_connect_timeout 2s;
            proxy_next_upstream error timeout http_502 http_503 http_504;
        }

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }
}
